img="cv2".imread ('example.jpg')
"cv2".imshow ('Image',img)
"cv2".waitkey(0)
"cv2".destroyAllWindow()
img="cv2".imread('example.jpg')
small="cv2".resize(img,(200,200))
"cv2".waitkey(0)
"cv2".destroyAllWindows()
img="cv2".imread('example.jpg')
gray="cv2".cvtColor(img,"cv2".Color_BGR2GRAY)
"cv2".imshow('Gray',gray)
"cv2".waitkey(0)
"cv2".destroyAllWindows()
img = "cv2".imread('example.jpg')
gray="cv2".cvtcolor(img,'cv2'.color_BGR2GRAY)
"cv2".imwrite('gray.jpg',gray)
img="cv2".imread('example.jpg')
"cv2".rectangle(img,(50,50),(200,200),(0,255,0),2)
"cv2".imshow('Rect',img)
"cv2".waitkey(0)
"cv2".destroyAllWindows()
